---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: centos-6.4
- name: centos-5.9

suites:
- name: default
  run_list:
    - "recipe[ceph]"
  attributes: &defaults
    ceph:
      config:
        fsid: ae3f1d03-bacd-4a90-b869-1a4fabb107f2
        mon_initial_members:
          - "127.0.0.1"
- name: repo
  run_list:
    - "recipe[ceph::repo]"
  attributes: *defaults
- name: osd
  run_list:
    - "recipe[ceph::osd]"
  attributes: *defaults
- name: mon
  run_list:
    - "recipe[ceph::mon]"
  attributes: *defaults
- name: mds
  run_list:
    - "recipe[ceph::mds]"
  attributes: *defaults
- name: radosgw
  run_list:
    - "recipe[ceph::radosgw]"
  attributes: *defaults
